# Leave blank, these are overwritten by command line defaults
hecatomb:
    args:
        reads:
        output:
        log:
        search:
        host:
        trim:
        combineRuns:
        hostFa:
        hostName:
        assembly:
        custom_aa:
        custom_nt:
        profile:
    immutable:
        reqAA:
            -a
            --tax-output-mode 2
            --search-type 2
            --tax-lineage 1
            --lca-ranks "superkingdom,phylum,class,order,family,genus,species"
            --format-output "query,target,evalue,pident,fident,nident,mismatch,qcov,tcov,qstart,qend,qlen,tstart,tend,tlen,alnlen,bits,qheader,theader,taxid,taxname,taxlineage"
        secondaryNtFormat:
            --format-output 'query,target,evalue,pident,fident,nident,mismatch,qcov,tcov,qstart,qend,qlen,tstart,tend,tlen,alnlen,bits'
        taxonkitReformat:
            -f '{k}\\t{p}\\t{c}\\t{o}\\t{f}\\t{g}\\t{s}' -F --fill-miss-rank
        mmseqsHeaderAA: "query\ttarget\tevalue\tpident\tfident\tnident\tmismatch\tqcov\ttcov\tqstart\tqend\tqlen\ttstart\ttend\ttlen\talnlen\tbits\tqheader\ttheader\ttaxid\ttaxname\tlineage"
        mmseqConvertAliFormat: "query,target,evalue,pident,fident,nident,mismatch,qcov,tcov,qstart,qend,qlen,tstart,tend,tlen,alnlen,bits,qheader,theader"
        contigAnnotHeader: "contigID\tevalue\tpident\tfident\tnident\tmismatch\tqcov\ttcov\tqstart\tqend\tqlen\ttstart\ttend\ttlen\talnlen\tbits\ttarget\tkingdom\tphylum\tclass\torder\tfamily\tgenus\tspecies"
        bigtableHeader:
            - seqID
            - sampleID
            - count
            - percent
            - alnType     # aa or nt
            - targetID
            - evalue
            - pident
            - fident
            - nident
            - mismatches
            - qcov
            - tcov
            - qstart
            - qend
            - qlen
            - tstart
            - tend
            - tlen
            - alnlen
            - bits
            - targetName
            - taxMethod
            - kingdom
            - phylum
            - class
            - order
            - family
            - genus
            - species
            - baltimoreType
            - baltimoreGroup
        contigTaxonHeader:
            - contigID
            - seqID
            - start
            - stop
            - len
            - qual
            - count
            - percent
            - alnType
            - taxMethod
            - kingdom
            - phylum
            - class
            - order
            - family
            - genus
            - species
            - baltimoreType
            - baltimoreGroup